### ISSUE TITLE
up&down issue

### ISSUE THREAD

**Issue by NeverMorewd** [vain0x/DotNetKit.Wpf.AutoCompleteComboBox#17] opened 2020-10-19 05:24 UTC
when I type a word the dropdown will show the items matched.And I can select one by Up and Down in keyboards,the edittextbox will changed base on my selection, and it keep all the text selected.There‘s no problem by now.
However,if I press a new key in keyboards at this time.the edittextbox and the dropdownlist will be changed correspondingly.But I cannot select the item in the dropdown list by Up and Down.unless empty the edittextbox

**Comment by NeverMorewd** [comment] 2020-10-19 05:26
Very grateful for your sharing.Your awesome code help me a lot!!

**Comment by NeverMorewd** [comment] 2020-10-19 06:11
I may solve this problem by adding a line: IsDropDownOpen = false in AutoCompleteComboBox.cs under line 182.
The reason seems that the DropdownList need get the focus again

**Comment by vain0x** [comment] 2021-06-27 01:55
Thanks and sorry for late response.

I tried in the demo app but I couldn't observe the problem... (at current master 39e1f0e)
I would be glad if reproduction code is given.

![combobox-screenshot](https://user-images.githubusercontent.com/6957032/123530508-14acb200-d736-11eb-9ea4-50def47382c0.gif)

**Comment by vain0x** [comment] 2023-04-02 02:33
Closing since not reproduced. Feel free to reopen if someone want discuss about this.

**Closed by vain0x** 2023-04-02 02:33 UTC
