### ISSUE TITLE
Item selection in ComboBox breaks if DisplayMemberPath and TextSearch.TextPath point to different properties

### ISSUE THREAD

**Issue by thatgim** [vain0x/DotNetKit.Wpf.AutoCompleteComboBox#19] opened 2021-06-23 12:05 UTC
https://github.com/vain0x/DotNetKit.Wpf.AutoCompleteComboBox/blob/39e1f0e2bfbf1f5dbc1bac1e5cf87e2f4d8a728d/DotNetKit.Wpf.AutoCompleteComboBox/Windows/Controls/AutoCompleteComboBox.xaml.cs#L173
`text` gets filled by resolving `DisplayMemberPath` and `TextFromItem(SelectedItem)` gets filled by resolving `TextSearch.TextPath`.
If these properties aren't set to the same/equivalent properties `SelectedItem` gets unset immediatly after selection.

I tried removing `TextFromItem(SelectedItem) == text` and it fixed this problem and didn't introduce any new problem as far as I can tell.

**Comment by vain0x** [comment] 2021-06-27 01:39
Thanks for suggestion.

I tried to reproduce your situation (SelectedItem is unset) in the demo app but couldn't...: https://github.com/vain0x/DotNetKit.Wpf.AutoCompleteComboBox/commit/08c474560c42d562ce835354529e1aa8736b49bf
It seems Text is filled by resolving `TextPath` rather than `DisplayPath`, as `TextFromItem` is.

I would be glad if a reproduction code is given.

**Comment by vain0x** [comment] 2023-04-02 02:39
Closing since not reproduced. Feel free to reopen if someone want to discuss about this.

**Closed by vain0x** 2023-04-02 02:39 UTC
